# PD Configuration.

name = "{{sys.hostname}}"
data-dir = "{{pkg.svc_data_path}}"

client-urls = "http://{{sys.ip}}:2379"
# if not set, use ${client-urls}
advertise-client-urls = ""

peer-urls = "http://{{sys.ip}}:2380"
# if not set, use ${peer-urls}
advertise-peer-urls = ""

initial-cluster = """
{{~#eachAlive svc.members as |member| ~}}
  {{~member.sys.hostname}}=http://{{member.sys.ip}}:2380{{~#unless @last~}},{{/unless~}}
{{~/eachAlive ~}}
"""
initial-cluster-state = "{{cfg.initial-cluster-state}}"
lease = {{cfg.lease}}
tso-save-interval = "{{cfg.tso-save-interval}}"
namespace-classifier = "{{cfg.namespace-classifier}}"

{{#if cfg.security}}
[security]
{{toToml cfg.security}}
{{/if}}

[log]
{{toToml cfg.log}}

[metric]
{{toToml cfg.metric}}

[schedule]
{{toToml cfg.schedule}}

[replication]
{{toToml cfg.replication}}

[label-property]
{{toToml cfg.label-property}}
