# PD Configuration.

name = "{{sys.hostname}}"
data-dir = "{{pkg.svc_data_path}}"

client-urls = "http://{{sys.ip}}:{{cfg.client-port}}"
# if not set, use ${client-urls}
advertise-client-urls = ""

peer-urls = "http://{{sys.ip}}:{{cfg.peer-port}}"
# if not set, use ${peer-urls}
advertise-peer-urls = ""

initial-cluster = """
{{~#eachAlive svc.members as |member| ~}}
  {{~member.sys.hostname}}=http://{{member.sys.ip}}:2380{{~#unless @last~}},{{/unless~}}
{{~/eachAlive ~}}
"""

{{toToml cfg}}
